### ISSUE TITLE
php artisan migrate yaptığımda hata alıyorum

### ISSUE THREAD

**Issue by szrcmk** [gorkembayraktar/surucu-kursu#1]
Merhaba, yazmış olduğun kodu localimde çalıştırıp test etmek istemiştim. Clone yaptıktan sonra öncelikle composer update yaptım fakat hata aldım. (settings tablosu ile ilgili) daha sonra php artisan migrate yapayım dedim onda da aşağıdaki gibi hata aldım.  Yardımcı olur musun ? 

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'janus.settings' doesn't exist (Connection: mysql, SQL: select * from `settings` where `autoload` = 1)

**Comment by gorkembayraktar** [comment]
Merhaba, projeyi tekrar indiriniz ve aşağıdaki yönergeyi takip ediniz.

## Kurulum
Projeyi locale aldıktan sonra aşağıda yer alan adımları uygulayınız.
#### 1) .env.example dosyasını düzenleyin
    - .env.example isimli dosyayı .env olarak yeniden adlandırın.
    -  Mysql'de veritabanı oluşturunuz. Oluşturduğunuz dbname .env dosyasında tanımlanmalıdır.
    - .env dosyasında konfigürasyon değerlerini localinizdeki bilgiler ile değiştiriniz.
```
    # APP_URL değerini çalışma dizininiz olarak tanımlayınız.
    APP_URL=http://localhost

    # Database Bilgileriniz
    DB_CONNECTION=mysql
    DB_HOST=127.0.0.1
    DB_PORT=3306
    DB_DATABASE=laravel
    DB_USERNAME=root
    DB_PASSWORD=
```
#### 2) Gereklik bağımlılıkların yüklenmesi
Paketlerin yüklenmesi için php paket yöneticisi composer kurulu olan bir ortamda aşadağıdaki komutu çalıştırınız.
```
composer install
```
Tabloların ve örnek datanın initialize işlemi
Uyarı: Tablolar mevcut ve data girdisi var ise tüm veriler silinecek ve tablolar varsayılan ayarlarda seed edilecektir.
```
php artisan migrate:refresh --seed
```
Proje için özel anahtar oluşturulması
```
php artisan key:generate
```
#### 3) Projeyi dev olarak çalıştır
Eğer projeyi dev olarak başlatırsanız, .env dosyasında APP_URL=http://localhost:<AÇILAN PORT> olarak tanımlama yapınız.
```
php artisan serve
```

#### 4) Projeyi Sunucuda Serve etmek
Production ortamında paket boyutunu küçültmek için yalnızca gerekli olan bağımlılıklar kullanılamalıdır. Dev dependencies paketlerinin kaldırılması ve optimizasyon işlemi için aşağıda yer alan komutu dizininizde çalıştırınız:
```
composer install --no-dev --optimize-autoloader
```
Projenizi uzak sunucuda çalıştırmak için: 

   - dizinde bulunan .htaccess.server dosya adını .htaccess olarak yeniden adlandırın.
